import type {
  CatalogData,
  EstimatorConfig,
  HardwareTier,
  ModelCatalogItem,
  PricingAssumptions,
  SecurityTier,
  ToolAddon
} from "./types";

export const initialEstimatorConfig: EstimatorConfig = {
  employees: 35,
  aiUsers: 12,
  simultaneousUsers: 4,
  usageLevel: "standard",
  documentCount: "1k-10k",
  totalFileSize: "10gb-100gb",
  typicalDocumentSize: "medium",
  fileTypes: ["PDF", "Word documents", "Excel spreadsheets"],
  workloads: ["Search documents", "Summarize documents", "Generate reports"],
  securityTier: "private-on-prem",
  performancePreference: "balanced",
  existingHardware: "new-hardware",
  budgetSensitivity: "balance-cost-performance"
};

export const modelCatalog: ModelCatalogItem[] = [
  {
    name: "Qwen3.6-35B-A3B",
    exactModelId: "qwen3.6-35b-a3b",
    provider: "Qwen",
    license: "To be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "Large Context AI",
    modelType: "Mixture-of-experts language model",
    totalParameters: "35B",
    activeParameters: "A3B",
    contextTokens: 131072,
    estimatedContextWords: 90000,
    maximumOutputTokens: 8192,
    modality: "Text",
    strengths: [
      "Strong balance of capability and hardware cost",
      "Long context",
      "Tool workflows",
      "Coding and developer workflows",
      "Document-heavy business use"
    ],
    weaknesses: [
      "Full long-context use still needs good hardware",
      "Model details must be periodically reviewed",
      "Regulated deployment requires validation"
    ],
    bestUseCases: [
      "SMB document AI",
      "Whole-folder analysis",
      "Long-document search",
      "Codebase assistance",
      "Scheduled agents",
      "Business workflow tools"
    ],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "high",
    codingAbility: "high",
    multimodalSupport: false,
    minimumVramGb: 24,
    recommendedVramGb: 48,
    minimumSystemRamGb: 64,
    recommendedSystemRamGb: 128,
    storageRequirementGb: 90,
    supportedRuntimes: ["vLLM", "Ollama", "llama.cpp-compatible runtime after validation"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "Medium",
    notes: "Likely best first practical model for Iron Point deployments after license and benchmark review.",
    sourceUrl: "To be reviewed"
  },
  {
    name: "gpt-oss-20b",
    exactModelId: "gpt-oss-20b",
    provider: "OpenAI community/open-weight ecosystem",
    license: "To be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "Basic Office AI",
    modelType: "Reasoning language model",
    totalParameters: "20B",
    activeParameters: "20B",
    contextTokens: 32768,
    estimatedContextWords: 22000,
    maximumOutputTokens: 4096,
    modality: "Text",
    strengths: [
      "Lower hardware requirement",
      "Good reasoning for size",
      "Good private assistant for smaller businesses",
      "Useful for pilots and lower-cost deployments"
    ],
    weaknesses: [
      "Less powerful than larger models",
      "Not ideal for very large document sets or advanced workflows"
    ],
    bestUseCases: ["Budget pilots", "Small business AI", "Simple private assistant", "Policy Q&A", "Summaries", "Basic tools"],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "medium",
    codingAbility: "medium",
    multimodalSupport: false,
    minimumVramGb: 16,
    recommendedVramGb: 24,
    minimumSystemRamGb: 32,
    recommendedSystemRamGb: 64,
    storageRequirementGb: 50,
    supportedRuntimes: ["Ollama", "vLLM", "llama.cpp-compatible runtime after validation"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "Low to medium",
    notes: "Good candidate for pilots where budget is the strongest constraint.",
    sourceUrl: "To be reviewed"
  },
  {
    name: "Mistral Small 3.x",
    exactModelId: "mistral-small-3x",
    provider: "Mistral AI",
    license: "To be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "Basic Office AI",
    modelType: "Efficient language model",
    totalParameters: "Small class",
    activeParameters: "Small class",
    contextTokens: 32768,
    estimatedContextWords: 22000,
    maximumOutputTokens: 4096,
    modality: "Text",
    strengths: [
      "Good general business assistant",
      "Lower hardware overhead",
      "Good for chat, summaries, and standard office documents",
      "Strong practical SMB option"
    ],
    weaknesses: [
      "Less deep reasoning than larger models",
      "Not the top choice for whole-company knowledge systems"
    ],
    bestUseCases: ["Standard office assistant", "Secure document search", "General Q&A", "Lower-cost business deployments"],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "medium",
    codingAbility: "medium",
    multimodalSupport: false,
    minimumVramGb: 12,
    recommendedVramGb: 24,
    minimumSystemRamGb: 32,
    recommendedSystemRamGb: 64,
    storageRequirementGb: 45,
    supportedRuntimes: ["Ollama", "vLLM"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "Low to medium",
    notes: "Efficient office default when long-context needs are modest.",
    sourceUrl: "To be reviewed"
  },
  {
    name: "Gemma 4 26B-A4B or Similar Efficient Gemma Model",
    exactModelId: "gemma-efficient-26b-a4b",
    provider: "Google / Gemma ecosystem",
    license: "To be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "Large Context AI",
    modelType: "Efficient language model",
    totalParameters: "26B class",
    activeParameters: "A4B or similar",
    contextTokens: 65536,
    estimatedContextWords: 45000,
    maximumOutputTokens: 4096,
    modality: "Text",
    strengths: [
      "Good efficiency",
      "Low hardware cost compared with larger models",
      "Useful for low-cost long-context systems",
      "Good candidate for small office private AI"
    ],
    weaknesses: [
      "License and business terms must be checked",
      "Actual performance should be validated before final recommendation"
    ],
    bestUseCases: ["Low-cost long-document AI", "Small office document search", "Summaries", "Internal assistant"],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "medium",
    codingAbility: "medium",
    multimodalSupport: false,
    minimumVramGb: 16,
    recommendedVramGb: 32,
    minimumSystemRamGb: 64,
    recommendedSystemRamGb: 96,
    storageRequirementGb: 65,
    supportedRuntimes: ["Ollama", "vLLM", "llama.cpp-compatible runtime after validation"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "Low to medium",
    notes: "Low-cost long-document candidate that should be validated for the exact workload.",
    sourceUrl: "To be reviewed"
  },
  {
    name: "Llama 3.3 70B Instruct",
    exactModelId: "llama-3.3-70b-instruct",
    provider: "Meta",
    license: "Meta Llama license to be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "Business Reasoning AI",
    modelType: "Dense language model",
    totalParameters: "70B",
    activeParameters: "70B",
    contextTokens: 131072,
    estimatedContextWords: 90000,
    maximumOutputTokens: 8192,
    modality: "Text",
    strengths: [
      "Strong general assistant",
      "Good summaries",
      "Good business Q&A",
      "Good policy and manual explanation",
      "Mature ecosystem"
    ],
    weaknesses: [
      "Hardware-heavy compared with smaller models",
      "License requires tracking",
      "Not as tool-focused or long-context-specialized as newer models"
    ],
    bestUseCases: ["General business assistant", "Larger office deployments", "Strong local Q&A"],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "medium",
    codingAbility: "medium",
    multimodalSupport: false,
    minimumVramGb: 48,
    recommendedVramGb: 80,
    minimumSystemRamGb: 128,
    recommendedSystemRamGb: 192,
    storageRequirementGb: 150,
    supportedRuntimes: ["vLLM", "Ollama", "llama.cpp-compatible runtime after validation"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "Medium to high",
    notes: "Mature general business model when hardware budget allows.",
    sourceUrl: "To be reviewed"
  },
  {
    name: "gpt-oss-120b",
    exactModelId: "gpt-oss-120b",
    provider: "OpenAI community/open-weight ecosystem",
    license: "To be reviewed before deployment",
    commercialUseAllowed: "unclear",
    releaseDate: "To be reviewed",
    lastReviewedDate: "2026-06-28",
    modelCategory: "High-Security AI",
    modelType: "High-reasoning language model",
    totalParameters: "120B",
    activeParameters: "120B",
    contextTokens: 65536,
    estimatedContextWords: 45000,
    maximumOutputTokens: 8192,
    modality: "Text",
    strengths: [
      "Strong reasoning",
      "Advanced document analysis",
      "Private/on-prem reasoning workloads",
      "Tool workflows",
      "Secure business assistant"
    ],
    weaknesses: [
      "Expensive hardware",
      "Not best for low-budget SMB installs",
      "Context may not handle extremely large document libraries all at once"
    ],
    bestUseCases: [
      "High-reasoning private AI",
      "Advanced legal and technical analysis",
      "Secure agentic workflows",
      "Customers with larger budgets"
    ],
    toolCallingSupport: true,
    structuredOutputSupport: true,
    agenticWorkflowSuitability: "high",
    codingAbility: "high",
    multimodalSupport: false,
    minimumVramGb: 96,
    recommendedVramGb: 160,
    minimumSystemRamGb: 192,
    recommendedSystemRamGb: 256,
    storageRequirementGb: 260,
    supportedRuntimes: ["vLLM", "custom validated runtime"],
    offlineCapable: true,
    airGapSuitable: true,
    hardwareCategory: "High",
    notes: "High-reasoning option for customers with strong security and performance needs.",
    sourceUrl: "To be reviewed"
  }
];

export const hardwareTiers: HardwareTier[] = [
  {
    slug: "entry-local-ai",
    tierName: "Entry Local AI",
    customerDescription: "A low-cost pilot or small-office setup for basic private document search and summaries.",
    minimumVramGb: 12,
    recommendedVramGb: 24,
    minimumRamGb: 32,
    recommendedRamGb: 64,
    cpuClass: "Modern workstation or modest server CPU",
    storageRecommendation: "1-2 TB NVMe storage, expandable",
    gpuExamples: ["RTX 4070 Ti Super class", "RTX 3090 class", "used workstation GPU after validation"],
    expectedUsers: "1-8 regular AI users",
    expectedDocumentWorkload: "Small office libraries, pilots, short summaries",
    estimatedHardwareCostLow: 2800,
    estimatedHardwareCostHigh: 6500,
    notes: "Best for pilots and cost-sensitive use where slower large-document answers are acceptable."
  },
  {
    slug: "standard-business-ai",
    tierName: "Standard Business AI",
    customerDescription: "Balanced daily private AI for a small team with normal document libraries and permissions.",
    minimumVramGb: 24,
    recommendedVramGb: 48,
    minimumRamGb: 64,
    recommendedRamGb: 128,
    cpuClass: "High-end workstation or small server CPU",
    storageRecommendation: "2-4 TB NVMe storage with backup plan",
    gpuExamples: ["RTX 4090 class", "RTX 6000 Ada class", "L40S class after validation"],
    expectedUsers: "5-25 regular AI users",
    expectedDocumentWorkload: "Normal SMB document libraries, scheduled reports, permissions",
    estimatedHardwareCostLow: 6500,
    estimatedHardwareCostHigh: 14500,
    notes: "Recommended default for most SMB deployments."
  },
  {
    slug: "high-performance-business-ai",
    tierName: "High-Performance Business AI",
    customerDescription: "A stronger local AI system for larger documents, more users, and background processing.",
    minimumVramGb: 48,
    recommendedVramGb: 80,
    minimumRamGb: 128,
    recommendedRamGb: 192,
    cpuClass: "Server-grade CPU with strong memory bandwidth",
    storageRecommendation: "4-8 TB NVMe storage with separate backup target",
    gpuExamples: ["RTX 6000 Ada class", "L40S class", "dual high-memory GPUs after validation"],
    expectedUsers: "15-60 regular AI users",
    expectedDocumentWorkload: "Large documents, scheduled summarization, heavier retrieval",
    estimatedHardwareCostLow: 14500,
    estimatedHardwareCostHigh: 32000,
    notes: "Useful when performance and future growth matter more than lowest initial cost."
  },
  {
    slug: "advanced-local-ai-server",
    tierName: "Advanced Local AI Server",
    customerDescription: "A department-scale server for large context, codebase tools, and heavier custom workflows.",
    minimumVramGb: 80,
    recommendedVramGb: 160,
    minimumRamGb: 192,
    recommendedRamGb: 256,
    cpuClass: "Multi-socket or high-core-count server platform",
    storageRecommendation: "8-20 TB fast storage with managed backup and retention",
    gpuExamples: ["multi-GPU RTX 6000 Ada class", "L40S multi-GPU class", "H100-class after assessment"],
    expectedUsers: "40-150 regular AI users",
    expectedDocumentWorkload: "Large context, codebases, heavy workflows, department-scale use",
    estimatedHardwareCostLow: 32000,
    estimatedHardwareCostHigh: 78000,
    notes: "Designed for bigger models, more concurrency, and custom workflow tooling."
  },
  {
    slug: "enterprise-air-gapped-ai-server",
    tierName: "Enterprise / Air-Gapped AI Server",
    customerDescription: "Dedicated high-security infrastructure with offline procedures, documentation, and controlled updates.",
    minimumVramGb: 96,
    recommendedVramGb: 160,
    minimumRamGb: 256,
    recommendedRamGb: 512,
    cpuClass: "Enterprise server platform with validated security controls",
    storageRecommendation: "Encrypted enterprise storage sized after data inventory",
    gpuExamples: ["validated enterprise GPU configuration", "multi-GPU server after security review"],
    expectedUsers: "Security-sensitive teams and larger installations",
    expectedDocumentWorkload: "Regulated, offline, or high-assurance workloads",
    estimatedHardwareCostLow: 55000,
    estimatedHardwareCostHigh: 150000,
    notes: "Final configuration depends heavily on facility, policy, compliance, and update requirements."
  }
];

export const securityTiers: SecurityTier[] = [
  {
    slug: "secure-connected",
    tierName: "Secure Connected AI",
    description:
      "AI may access approved cloud or remote documents. Processing is controlled and company documents are not used to train public AI models.",
    internetAccessAllowed: true,
    localProcessingRequired: false,
    airGapRequired: false,
    auditLoggingRequired: false,
    roleBasedAccessRequired: true,
    offlineUpdateProcedureRequired: false,
    complianceDocumentationRequired: false,
    estimatedImplementationComplexity: 2,
    costMultiplier: 1,
    notes: "Good for businesses that need controlled AI but can use approved connected services."
  },
  {
    slug: "private-on-prem",
    tierName: "Private On-Prem AI",
    description:
      "AI runs on company-owned hardware. Documents remain inside the company network, with internet restricted or allowlisted as needed.",
    internetAccessAllowed: true,
    localProcessingRequired: true,
    airGapRequired: false,
    auditLoggingRequired: true,
    roleBasedAccessRequired: true,
    offlineUpdateProcedureRequired: false,
    complianceDocumentationRequired: false,
    estimatedImplementationComplexity: 4,
    costMultiplier: 1.25,
    notes: "Recommended default for businesses that want private AI around internal documents."
  },
  {
    slug: "offline-air-gapped",
    tierName: "Offline / Air-Gapped AI",
    description:
      "AI system has no internet access. Updates and model files move through controlled offline procedures.",
    internetAccessAllowed: false,
    localProcessingRequired: true,
    airGapRequired: true,
    auditLoggingRequired: true,
    roleBasedAccessRequired: true,
    offlineUpdateProcedureRequired: true,
    complianceDocumentationRequired: true,
    estimatedImplementationComplexity: 7,
    costMultiplier: 1.75,
    notes: "Offline systems require careful update, logging, backup, and operational procedures."
  },
  {
    slug: "regulated-high-assurance",
    tierName: "Regulated / CUI / High-Assurance AI",
    description:
      "For CUI, FCI, legal privilege, medical-adjacent data, export-controlled data, defense-related data, or compliance-heavy environments.",
    internetAccessAllowed: false,
    localProcessingRequired: true,
    airGapRequired: false,
    auditLoggingRequired: true,
    roleBasedAccessRequired: true,
    offlineUpdateProcedureRequired: true,
    complianceDocumentationRequired: true,
    estimatedImplementationComplexity: 8,
    costMultiplier: 2,
    notes: "Requires a technical and compliance review before recommendations are final."
  },
  {
    slug: "classified-support",
    tierName: "Classified Environment Support",
    description:
      "Available only under proper customer sponsorship, approved facility/security requirements, and applicable legal/security authority.",
    internetAccessAllowed: false,
    localProcessingRequired: true,
    airGapRequired: true,
    auditLoggingRequired: true,
    roleBasedAccessRequired: true,
    offlineUpdateProcedureRequired: true,
    complianceDocumentationRequired: true,
    estimatedImplementationComplexity: 10,
    costMultiplier: 2.8,
    notes: "This website cannot receive classified information. Discussion requires proper channels and authority."
  }
];

export const toolAddons: ToolAddon[] = [
  {
    slug: "secure-document-indexing",
    name: "Secure document indexing",
    description: "Create a searchable private index of approved company document locations.",
    complexity: "medium",
    estimatedSetupCostLow: 2500,
    estimatedSetupCostHigh: 6500,
    monthlySupportImpact: 250,
    requiredSecurityConsiderations: "Index storage, access controls, backup, and retention policy.",
    notes: "Core add-on for most private document AI systems."
  },
  {
    slug: "folder-monitoring",
    name: "Folder monitoring",
    description: "Watch approved folders for changes so the AI index stays current.",
    complexity: "medium",
    estimatedSetupCostLow: 1500,
    estimatedSetupCostHigh: 4500,
    monthlySupportImpact: 150,
    requiredSecurityConsiderations: "File share permissions and service-account scope.",
    notes: "Useful when documents change often."
  },
  {
    slug: "scheduled-folder-scans",
    name: "Scheduled folder scans",
    description: "Run controlled scans on a defined schedule instead of constant monitoring.",
    complexity: "low",
    estimatedSetupCostLow: 900,
    estimatedSetupCostHigh: 2500,
    monthlySupportImpact: 100,
    requiredSecurityConsiderations: "Scan windows, logs, and approved paths.",
    notes: "Good fit for lower-change document stores."
  },
  {
    slug: "background-document-summaries",
    name: "Background document summaries",
    description: "Prepare summaries in the background for faster review and reporting.",
    complexity: "medium",
    estimatedSetupCostLow: 2200,
    estimatedSetupCostHigh: 7000,
    monthlySupportImpact: 250,
    requiredSecurityConsiderations: "Summary storage inherits document access controls.",
    notes: "Can increase hardware needs for large libraries."
  },
  {
    slug: "user-groups-permissions",
    name: "User groups and permissions",
    description: "Filter answers and citations based on each user group or role.",
    complexity: "high",
    estimatedSetupCostLow: 4500,
    estimatedSetupCostHigh: 14000,
    monthlySupportImpact: 450,
    requiredSecurityConsiderations: "Identity source, group sync, permission testing, audit logs.",
    notes: "Important when not all users can see all documents."
  },
  {
    slug: "source-citations",
    name: "Source citations",
    description: "Show answer citations that point back to approved source documents.",
    complexity: "low",
    estimatedSetupCostLow: 1200,
    estimatedSetupCostHigh: 3500,
    monthlySupportImpact: 100,
    requiredSecurityConsiderations: "Citation paths must not reveal restricted files to unauthorized users.",
    notes: "Recommended for trust and reviewability."
  },
  {
    slug: "database-lookup",
    name: "Database lookup",
    description: "Let AI workflows retrieve approved read-only database records.",
    complexity: "high",
    estimatedSetupCostLow: 6500,
    estimatedSetupCostHigh: 20000,
    monthlySupportImpact: 600,
    requiredSecurityConsiderations: "Read-only credentials, query allowlists, logs, and network access.",
    notes: "Requires technical review before compatibility is promised."
  },
  {
    slug: "email-ticket-summarization",
    name: "Email or ticket summarization",
    description: "Summarize approved email exports, help desk tickets, or shared mailbox content.",
    complexity: "medium",
    estimatedSetupCostLow: 2800,
    estimatedSetupCostHigh: 8500,
    monthlySupportImpact: 300,
    requiredSecurityConsiderations: "Mailbox scope, retention, PII handling, and access review.",
    notes: "No live mailbox integration is included in the MVP estimate without review."
  },
  {
    slug: "scheduled-reports",
    name: "Scheduled reports",
    description: "Generate recurring read-only reports from approved indexed sources.",
    complexity: "medium",
    estimatedSetupCostLow: 3200,
    estimatedSetupCostHigh: 9500,
    monthlySupportImpact: 350,
    requiredSecurityConsiderations: "Recipients, report storage, schedule logs, and review workflow.",
    notes: "Often paired with background summaries."
  },
  {
    slug: "contract-comparison",
    name: "Contract comparison",
    description: "Compare approved contract versions and flag differences for review.",
    complexity: "high",
    estimatedSetupCostLow: 5000,
    estimatedSetupCostHigh: 18000,
    monthlySupportImpact: 450,
    requiredSecurityConsiderations: "Legal privilege, access control, and human review language.",
    notes: "Not a replacement for legal advice."
  },
  {
    slug: "policy-qa",
    name: "Policy Q&A",
    description: "Answer questions against approved policies, manuals, and procedures with citations.",
    complexity: "medium",
    estimatedSetupCostLow: 2200,
    estimatedSetupCostHigh: 7000,
    monthlySupportImpact: 250,
    requiredSecurityConsiderations: "Version control, citations, and reviewer ownership.",
    notes: "Common first workflow for operations teams."
  },
  {
    slug: "codebase-search",
    name: "Codebase search",
    description: "Search and explain approved repositories in a private local AI workflow.",
    complexity: "high",
    estimatedSetupCostLow: 5000,
    estimatedSetupCostHigh: 16000,
    monthlySupportImpact: 450,
    requiredSecurityConsiderations: "Repository access, secrets scanning, and no source upload through the website.",
    notes: "Requires repository review outside this public website."
  },
  {
    slug: "developer-assistant-integration",
    name: "Developer assistant integration",
    description: "Connect private AI to developer tools for code explanation and workflow support.",
    complexity: "high",
    estimatedSetupCostLow: 6500,
    estimatedSetupCostHigh: 24000,
    monthlySupportImpact: 600,
    requiredSecurityConsiderations: "IDE/tool permissions, repository access, and audit expectations.",
    notes: "Can require stronger hardware for code-heavy context."
  },
  {
    slug: "custom-workflow-tool",
    name: "Custom workflow tool",
    description: "Build a business-specific AI workflow around approved data and review steps.",
    complexity: "custom",
    estimatedSetupCostLow: 8000,
    estimatedSetupCostHigh: 40000,
    monthlySupportImpact: 700,
    requiredSecurityConsiderations: "Depends on workflow, data source, and approval process.",
    notes: "Requires scoping before final pricing."
  },
  {
    slug: "audit-logs",
    name: "Audit logs",
    description: "Capture important system events, user actions, and workflow activity for review.",
    complexity: "medium",
    estimatedSetupCostLow: 3000,
    estimatedSetupCostHigh: 9000,
    monthlySupportImpact: 300,
    requiredSecurityConsiderations: "Log retention, restricted access, and review ownership.",
    notes: "Recommended for regulated or high-assurance deployments."
  },
  {
    slug: "admin-dashboard",
    name: "Admin dashboard",
    description: "Provide operational visibility into indexing, users, workflows, and lead review.",
    complexity: "medium",
    estimatedSetupCostLow: 3500,
    estimatedSetupCostHigh: 12000,
    monthlySupportImpact: 350,
    requiredSecurityConsiderations: "Admin roles, access logging, and least privilege.",
    notes: "The website MVP includes lead/admin basics; production AI admin tooling is separate."
  },
  {
    slug: "offline-update-package-support",
    name: "Offline update package support",
    description: "Plan controlled movement of approved model and software updates into offline environments.",
    complexity: "high",
    estimatedSetupCostLow: 7000,
    estimatedSetupCostHigh: 28000,
    monthlySupportImpact: 600,
    requiredSecurityConsiderations: "Media handling, hashes, approvals, and documented procedure.",
    notes: "Required for air-gapped environments."
  },
  {
    slug: "ocr-processing",
    name: "Scanned document OCR",
    description: "Prepare scanned PDFs and image files for private search and summaries.",
    complexity: "medium",
    estimatedSetupCostLow: 2500,
    estimatedSetupCostHigh: 9000,
    monthlySupportImpact: 300,
    requiredSecurityConsiderations: "OCR output inherits source document sensitivity and retention rules.",
    notes: "Recommended when scanned PDFs or images are part of the document library."
  }
];

export const pricingAssumptions: PricingAssumptions = {
  id: "default",
  baseInstallationLow: 7500,
  baseInstallationHigh: 18000,
  customDevelopmentHourlyEstimate: 175,
  monthlySupportLow: 750,
  monthlySupportHigh: 2200,
  assessmentPrice: 750,
  foundingCustomerDiscountPercent: 0,
  notes:
    "Preliminary MVP assumptions only. Final pricing requires technical assessment, data inventory, and hardware review."
};

export const catalogData: CatalogData = {
  models: modelCatalog,
  hardwareTiers,
  securityTiers,
  toolAddons,
  pricing: pricingAssumptions
};
